services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service

    environment:
      - DB_HOST=database
      - DB_NAME=service
      - DB_USER=root
      - DB_PASS=1234

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234